#!/bin/bash
# Write / remove the Android upload keystore and android/key.properties.
#
#   signing.sh write [--allow-missing]   (run from the app root)
#   signing.sh cleanup
#
# Env: ANDROID_KEYSTORE_BASE64, ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_ALIAS,
#      ANDROID_KEY_PASSWORD.
# The keystore goes to a private temp dir outside the repo. key.properties
# uses the standard Flutter format (storeFile, storePassword, keyAlias,
# keyPassword) that android/app/build.gradle(.kts) reads.
# Secrets are never printed.
set -euo pipefail

_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/common/util.sh
source "$_DIR/../common/util.sh"

KEY_PROPERTIES="android/key.properties"
MARKER="# generated by flutter-ci; deleted after the build"

_escape_prop() {
  # Java .properties: escape backslashes.
  printf '%s' "$1" | sed 's/\\/\\\\/g'
}

signing_write() {
  local allow_missing="${1:-}"
  local missing=() v
  for v in ANDROID_KEYSTORE_BASE64 ANDROID_KEYSTORE_PASSWORD ANDROID_KEY_ALIAS ANDROID_KEY_PASSWORD; do
    [[ -n "${!v:-}" ]] || missing+=("$v")
  done
  if [[ ${#missing[@]} -gt 0 ]]; then
    if [[ "$allow_missing" == "--allow-missing" ]]; then
      log_warn "Signing secrets missing (${missing[*]}); dry-run continues with the app's fallback signing config."
      return 0
    fi
    die "Missing signing secrets: ${missing[*]}. Pass them from your caller workflow." "SECRETS.md#android-signing"
  fi

  [[ -d android ]] || die "No android/ directory in $(pwd). Is app-directory set correctly?" "TROUBLESHOOTING.md#android-build-fails"
  if git ls-files --error-unmatch "$KEY_PROPERTIES" >/dev/null 2>&1; then
    die "$KEY_PROPERTIES is committed to git. Remove it from the repo (git rm --cached) and add it to .gitignore; CI writes it from secrets." \
      "SECRETS.md#android-signing"
  fi

  mask "$ANDROID_KEYSTORE_PASSWORD"
  mask "$ANDROID_KEY_PASSWORD"

  local dir keystore
  dir="$(ci_temp_dir)"
  keystore="$dir/upload-keystore.jks"
  if ! printf '%s' "$ANDROID_KEYSTORE_BASE64" | b64decode | write_secret_file "$keystore" || [[ ! -s "$keystore" ]]; then
    die "ANDROID_KEYSTORE_BASE64 is not valid base64." "SECRETS.md#android-signing"
  fi

  if command -v keytool >/dev/null 2>&1; then
    if ! keytool -list -keystore "$keystore" -storepass:env ANDROID_KEYSTORE_PASSWORD -alias "$ANDROID_KEY_ALIAS" >/dev/null 2>&1; then
      rm -f "$keystore"
      die "The keystore could not be opened with ANDROID_KEYSTORE_PASSWORD, or it has no alias ANDROID_KEY_ALIAS." "SECRETS.md#android-signing"
    fi
  fi

  {
    printf '%s\n' "$MARKER"
    printf 'storeFile=%s\n' "$(_escape_prop "$keystore")"
    printf 'storePassword=%s\n' "$(_escape_prop "$ANDROID_KEYSTORE_PASSWORD")"
    printf 'keyAlias=%s\n' "$(_escape_prop "$ANDROID_KEY_ALIAS")"
    printf 'keyPassword=%s\n' "$(_escape_prop "$ANDROID_KEY_PASSWORD")"
  } | write_secret_file "$KEY_PROPERTIES"
  log_info "Wrote $KEY_PROPERTIES and the upload keystore (outside the repo)."
}

signing_cleanup() {
  if [[ -f "$KEY_PROPERTIES" ]] && head -n 1 "$KEY_PROPERTIES" | grep -qF "$MARKER"; then
    rm -f "$KEY_PROPERTIES"
  fi
  rm -f "$(ci_temp_dir)/upload-keystore.jks"
  log_info "Signing files removed."
}

case "${1:-}" in
  write) signing_write "${2:-}" ;;
  cleanup) signing_cleanup ;;
  *) echo "usage: signing.sh write [--allow-missing] | cleanup" >&2; exit 2 ;;
esac
