#!/bin/bash
# Generate ios/Flutter/Environment.xcconfig content for an environment.
#
# CLI: ios_xcconfig.sh <config.yaml> <env>    prints the file content
#
# One-time app setup (docs/NEW_PROJECT_SETUP.md): Release.xcconfig ends with
#   #include? "Environment.xcconfig"
# and Info.plist uses $(APP_DISPLAY_NAME). Settings that are not configured
# are left out so the defaults in Release.xcconfig apply.

_IOS_XCCONFIG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/common/read_config.sh
source "$_IOS_XCCONFIG_DIR/read_config.sh"

ios_xcconfig() {
  local config="$1" env="$2" e=".environments.$2.ios" v
  config_load "$config"
  printf '// Generated by flutter-ci for the "%s" environment. Do not edit or commit.\n' "$env"
  v="$(cfg "$e.display_name")"
  [[ -n "$v" ]] && printf 'APP_DISPLAY_NAME = %s\n' "$v"
  v="$(cfg "$e.app_icon")"
  [[ -n "$v" ]] && printf 'ASSETCATALOG_COMPILER_APPICON_NAME = %s\n' "$v"
  yq e "($e.build_settings // {}) | to_entries | .[] | .key + \" = \" + (.value | tostring)" "$FLUTTER_CI_CONFIG"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  set -euo pipefail
  [[ $# -eq 2 ]] || { echo "usage: ios_xcconfig.sh <config.yaml> <env>" >&2; exit 2; }
  ensure_yq
  ios_xcconfig "$1" "$2"
fi
