#!/usr/bin/env bats
load helpers/common

XC="$BATS_TEST_DIRNAME/../scripts/xcode-cloud"

setup() {
  setup_tmp
  export CI_PRIMARY_REPOSITORY_PATH="$TMP/repo"
  mkdir -p "$TMP/repo/.flutter-ci" "$TMP/repo/ios"
}
teardown() { teardown_tmp; }

@test "ios xcconfig: display name, icon and extra settings" {
  write_valid_config "$TMP/c.yaml"
  run "$SCRIPTS/ios_xcconfig.sh" "$TMP/c.yaml" uat
  [ "$status" -eq 0 ]
  [[ "${lines[0]}" == "// Generated by flutter-ci"* ]]
  [ "${lines[1]}" = "APP_DISPLAY_NAME = MyApp UAT" ]
  [ "${lines[2]}" = "ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon-UAT" ]
  [ "${lines[3]}" = "MY_SETTING = abc" ]
}

@test "ios xcconfig: unset values are left out" {
  printf 'version: 1\napp: {name: X}\nenvironments:\n  prod: {}\n' >"$TMP/c.yaml"
  run "$SCRIPTS/ios_xcconfig.sh" "$TMP/c.yaml" prod
  [ "$status" -eq 0 ]
  [ "${#lines[@]}" -eq 1 ]
}

@test "post_clone: requires CI_TAG with guidance" {
  unset CI_TAG
  run "$XC/post_clone.sh"
  [ "$status" -eq 1 ]
  [[ "$output" == *"ERROR: CI_TAG is not set"*"XCODE_CLOUD_SETUP.md#start-condition"* ]]
}

@test "post_xcodebuild: no-op unless archive" {
  CI_XCODEBUILD_ACTION=build run "$XC/post_xcodebuild.sh"
  [ "$status" -eq 0 ]
  [[ "$output" == *"nothing to do"* ]]
}

@test "post_xcodebuild: writes labeled WhatToTest under 1 KB" {
  git_q init "$TMP/repo"
  cd "$TMP/repo"
  for i in 1 2 3 4 5 6 7; do git_q commit --allow-empty -m "$(printf 'Feature %s %0300d' "$i" 0)"; done
  cat >"$TMP/repo/.flutter-ci/state.env" <<STATE
TAG=v1.4.0
ENVIRONMENT=prod
ENV_LABEL=PROD
VERSION_NAME_FULL=1.4.0
APP_NAME=MyApp
FIREBASE_ENABLED=false
DRIVE_ENABLED=false
BUILD_NUMBER=9
COMMIT=$(git rev-parse HEAD)
APP_ROOT=$TMP/repo
STATE
  CI_XCODEBUILD_ACTION=archive run "$XC/post_xcodebuild.sh"
  [ "$status" -eq 0 ]
  f="$TMP/repo/ios/TestFlight/WhatToTest.en-US.txt"
  [[ "$(head -n 1 "$f")" == "[PROD] v1.4.0 · "* ]]
  [ "$(LC_ALL=C wc -c <"$f" | tr -d ' ')" -lt 1024 ]
}

@test "post_xcodebuild: missing ad hoc IPA is reported but not fatal" {
  git_q init "$TMP/repo"
  cd "$TMP/repo" && git_q commit --allow-empty -m x
  cat >"$TMP/repo/.flutter-ci/state.env" <<STATE
TAG=v1.4.0-beta.1
ENVIRONMENT=uat
ENV_LABEL=UAT
VERSION_NAME_FULL=1.4.0-beta.1
APP_NAME=MyApp
FIREBASE_ENABLED=true
FIREBASE_GROUPS=qa
FIREBASE_TESTERS=
DRIVE_ENABLED=false
DRIVE_FOLDER_ID=
BUILD_NUMBER=9
COMMIT=$(git rev-parse HEAD)
APP_ROOT=$TMP/repo
STATE
  CI_XCODEBUILD_ACTION=archive run "$XC/post_xcodebuild.sh"
  [ "$status" -eq 0 ]
  [[ "$output" == *"No ad hoc IPA found"* ]]
  CI_XCODEBUILD_ACTION=archive FLUTTER_CI_STRICT=1 run "$XC/post_xcodebuild.sh"
  [ "$status" -eq 1 ]
}

@test "post_xcodebuild: missing state fails clearly" {
  CI_XCODEBUILD_ACTION=archive run "$XC/post_xcodebuild.sh"
  [ "$status" -eq 1 ]
  [[ "$output" == *"ci_post_clone.sh did not finish"* ]]
}

@test "bootstrap templates are tiny, bash and executable" {
  for f in "$REPO_ROOT"/templates/ios/ci_scripts/*.sh; do
    [ -x "$f" ]
    [ "$(head -n 1 "$f")" = "#!/bin/bash" ]
    [ "$(wc -l <"$f" | tr -d ' ')" -le 12 ]
  done
}
