#!/usr/bin/env bats
load helpers/common

XC="$BATS_TEST_DIRNAME/../scripts/xcode-cloud"

setup() {
  setup_tmp
  export CI_PRIMARY_REPOSITORY_PATH="$TMP/repo"
  mkdir -p "$TMP/repo/.flutter-ci" "$TMP/repo/ios"
}
teardown() { teardown_tmp; }

@test "ios xcconfig: display name, icon and extra settings" {
  write_valid_config "$TMP/c.yaml"
  run "$SCRIPTS/ios_xcconfig.sh" "$TMP/c.yaml" uat
  [ "$status" -eq 0 ]
  [[ "${lines[0]}" == "// Generated by flutter-ci"* ]]
  [ "${lines[1]}" = "APP_DISPLAY_NAME = MyApp UAT" ]
  [ "${lines[2]}" = "ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon-UAT" ]
  [ "${lines[3]}" = "MY_SETTING = abc" ]
}

@test "ios xcconfig: unset values are left out" {
  printf 'version: 1\napp: {name: X}\nenvironments:\n  prod: {}\n' >"$TMP/c.yaml"
  run "$SCRIPTS/ios_xcconfig.sh" "$TMP/c.yaml" prod
  [ "$status" -eq 0 ]
  [ "${#lines[@]}" -eq 1 ]
}

@test "post_clone: requires CI_TAG with guidance" {
  unset CI_TAG
  run "$XC/post_clone.sh"
  [ "$status" -eq 1 ]
  [[ "$output" == *"ERROR: CI_TAG is not set"*"XCODE_CLOUD_SETUP.md#4-create-the-workflow"* ]]
}

@test "post_xcodebuild: no-op unless archive" {
  CI_XCODEBUILD_ACTION=build run "$XC/post_xcodebuild.sh"
  [ "$status" -eq 0 ]
  [[ "$output" == *"nothing to do"* ]]
}

@test "post_xcodebuild: missing state only warns" {
  CI_XCODEBUILD_ACTION=archive run "$XC/post_xcodebuild.sh"
  [ "$status" -eq 0 ]
  [[ "$output" == *"ci_post_clone.sh did not finish"* ]]
}

@test "bootstrap templates are tiny, bash and executable" {
  for f in "$REPO_ROOT"/templates/ios/ci_scripts/*.sh; do
    [ -x "$f" ]
    [ "$(head -n 1 "$f")" = "#!/bin/bash" ]
    [ "$(wc -l <"$f" | tr -d ' ')" -le 12 ]
  done
}
